"Main interface for iam service"

from mypy_boto3_iam.client import Client
from mypy_boto3_iam.helpers import (
    boto3_client,
    boto3_resource,
    get_get_account_authorization_details_paginator,
    get_get_group_paginator,
    get_instance_profile_exists_waiter,
    get_list_access_keys_paginator,
    get_list_account_aliases_paginator,
    get_list_attached_group_policies_paginator,
    get_list_attached_role_policies_paginator,
    get_list_attached_user_policies_paginator,
    get_list_entities_for_policy_paginator,
    get_list_group_policies_paginator,
    get_list_groups_for_user_paginator,
    get_list_groups_paginator,
    get_list_instance_profiles_for_role_paginator,
    get_list_instance_profiles_paginator,
    get_list_mfa_devices_paginator,
    get_list_policies_paginator,
    get_list_policy_versions_paginator,
    get_list_role_policies_paginator,
    get_list_roles_paginator,
    get_list_server_certificates_paginator,
    get_list_signing_certificates_paginator,
    get_list_ssh_public_keys_paginator,
    get_list_user_policies_paginator,
    get_list_users_paginator,
    get_list_virtual_mfa_devices_paginator,
    get_policy_exists_waiter,
    get_role_exists_waiter,
    get_simulate_custom_policy_paginator,
    get_simulate_principal_policy_paginator,
    get_user_exists_waiter,
)
from mypy_boto3_iam.service_resource import ServiceResource


__all__ = (
    "Client",
    "ServiceResource",
    "boto3_client",
    "boto3_resource",
    "get_get_account_authorization_details_paginator",
    "get_get_group_paginator",
    "get_list_access_keys_paginator",
    "get_list_account_aliases_paginator",
    "get_list_attached_group_policies_paginator",
    "get_list_attached_role_policies_paginator",
    "get_list_attached_user_policies_paginator",
    "get_list_entities_for_policy_paginator",
    "get_list_group_policies_paginator",
    "get_list_groups_paginator",
    "get_list_groups_for_user_paginator",
    "get_list_instance_profiles_paginator",
    "get_list_instance_profiles_for_role_paginator",
    "get_list_mfa_devices_paginator",
    "get_list_policies_paginator",
    "get_list_policy_versions_paginator",
    "get_list_role_policies_paginator",
    "get_list_roles_paginator",
    "get_list_ssh_public_keys_paginator",
    "get_list_server_certificates_paginator",
    "get_list_signing_certificates_paginator",
    "get_list_user_policies_paginator",
    "get_list_users_paginator",
    "get_list_virtual_mfa_devices_paginator",
    "get_simulate_custom_policy_paginator",
    "get_simulate_principal_policy_paginator",
    "get_instance_profile_exists_waiter",
    "get_policy_exists_waiter",
    "get_role_exists_waiter",
    "get_user_exists_waiter",
)
